### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by ilyaskarim** [sarala-io/sarala-json-api-data-formatter#4]
There is an error in this file while using with sarala Model: 

https://github.com/sarala-io/sarala-json-api-data-formatter/blob/master/src/Formatter.js#L119

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at eval (Formatter.js?8709:158)
    at arrayEach (lodash.js?2ef0:516)
    at Function.forEach (lodash.js?2ef0:9344)
    at Formatter.mapAndKillProps (Formatter.js?8709:157)
    at eval (Formatter.js?8709:207)
    at arrayEach (lodash.js?2ef0:516)
    at Function.forEach (lodash.js?2ef0:9344)
    at Formatter.serializeOne (Formatter.js?8709:205)
    at Formatter.serializeRelationship (Formatter.js?8709:255)
    at eval (Formatter.js?8709:266)

**Comment by milroyfraser** [comment]
Hi @ilyaskarim ,

Very sorry for the late late reply. This issue is been fixed in the v2.0.0

**Comment by maniyadv** [comment]
Hi @milroyfraser 
I am still getting this error in Saralajs package - "sarala": "^0.3.10",
It happens only when you find a resource and try to update any of its fields.
It works fine when you create a new resource. Saraljs might not be on the latest version of this package.
 
ie.
 
```javascript
let address = new Address();
let addressResource = await address.find(addressId)
addressResource.line_1 = "new line 1"
addressResource.save() // throws same error above
```
